language: r
cache: packages

matrix:
  include:
  - r: devel
  - r: release

env:
  global:
#  - _R_CHECK_FORCE_SUGGESTS_=false
  - _R_CHECK_FORCE_SUGGESTS_=true

# needed to install the magick package
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev


after_success:
  - Rscript -e 'covr::codecov()'
